# /// script
# dependencies = ["httpx"]
# requires-python = ">=3.14"
# ///
"""Fetch Pokemon names, types, and moves from PokeAPI and update pokemon_data.py."""

import textwrap
from pathlib import Path

import httpx

POKEAPI_BASE = "https://pokeapi.co/api/v2"
TARGET = Path(__file__).resolve().parent.parent / "src" / "faker_pokemon" / "pokemon_data.py"


def fetch_names(client: httpx.Client) -> tuple[str, ...]:
    r = client.get(f"{POKEAPI_BASE}/pokemon-species?limit=2000")
    r.raise_for_status()
    species = r.json()["results"]
    # Sort by pokedex number (extracted from URL: .../pokemon-species/{id}/)
    species.sort(key=lambda s: int(s["url"].rstrip("/").split("/")[-1]))
    return tuple(s["name"].capitalize() for s in species)


def fetch_types(client: httpx.Client) -> tuple[str, ...]:
    r = client.get(f"{POKEAPI_BASE}/type")
    r.raise_for_status()
    return tuple(
        t["name"].capitalize()
        for t in r.json()["results"]
        if t["name"] not in ("unknown", "shadow")
    )


def fetch_moves(client: httpx.Client) -> tuple[str, ...]:
    r = client.get(f"{POKEAPI_BASE}/move?limit=2000")
    r.raise_for_status()
    return tuple(m["name"].replace("-", " ").title() for m in r.json()["results"])


def format_tuple(name: str, items: tuple[str, ...]) -> str:
    entries = "\n".join(f'    "{item}",' for item in items)
    return f"{name}: tuple[str, ...] = (\n{entries}\n)"


def main() -> None:
    with httpx.Client(timeout=30) as client:
        print("Fetching pokemon names...")
        names = fetch_names(client)
        print(f"  {len(names)} pokemon")

        print("Fetching types...")
        types = fetch_types(client)
        print(f"  {len(types)} types")

        print("Fetching moves...")
        moves = fetch_moves(client)
        print(f"  {len(moves)} moves")

    content = textwrap.dedent("""\
        \"\"\"Pokemon data for the faker_pokemon provider.

        Auto-generated by scripts/update_data.py from PokeAPI (https://pokeapi.co/).
        Do not edit manually.
        \"\"\"

    """)
    content += "# All Pokemon names, National Pokedex order\n"
    content += format_tuple("POKEMON_NAMES", names)
    content += "\n\n# All 18 Pokemon types\n"
    content += format_tuple("POKEMON_TYPES", types)
    content += "\n\n# All Pokemon moves\n"
    content += format_tuple("POKEMON_MOVES", moves)
    content += "\n"

    TARGET.write_text(content)
    print(f"\nWritten to {TARGET}")


if __name__ == "__main__":
    main()
